import subprocess as sp
import sys as sy

import tomllib as tml

# -------------------------------
# Load command dictionary
# -------------------------------
with open("cmddict.toml", "rb") as f:
    cmds = tml.load(f)


# -------------------------------
# Parse .mtr file
# -------------------------------
def parse(text):
    lines = text.split(".")
    in_code = False
    cms = []

    for l in lines:
        line = l.strip()

        if not line:
            continue

        if line == "#startfile":
            in_code = True
            continue

        if line == "#endfile":
            break

        if not in_code:
            continue

        # remove $ comments
        line = line.split("$")[0].strip()

        if line:
            cms.append(line)

    return cms


# -------------------------------
# Translate to PowerShell
# -------------------------------
def translate(cms):
    pwshcmd = []

    for cmd in cms:
        parts = cmd.split()
        name = parts[0]
        args = parts[1:]

        if name not in cmds:
            raise ValueError(f"Command '{name}' not found")

        template = cmds[name]

        if "{args}" in template:
            pwshcmd.append(template.format(args=" ".join(args)))
        else:
            pwshcmd.append(template)

    return pwshcmd


# -------------------------------
# Write PowerShell file
# -------------------------------
def writing(pwshcmd):
    content = ["# generated by mtr", "$ErrorActionPreference = 'Stop'", ""]
    content.extend(pwshcmd)

    with open("runtime.ps1", "w", encoding="utf-8") as f:
        f.write("\n".join(content))


# -------------------------------
# Execute PowerShell (new window)
# -------------------------------
def execute():
    sp.Popen(
        [
            "powershell.exe",
            "-NoExit",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            "runtime.ps1",
        ]
    )


# -------------------------------
# Main
# -------------------------------
def main():
    if len(sy.argv) != 2:
        print("Usage: python main.py <input_file>.mtr")
        return

    filename = sy.argv[1]

    if not filename.endswith(".mtr"):
        print("Error: input file must have .mtr extension")
        return

    with open(filename, "r", encoding="utf-8") as f:
        text = f.read()

    try:
        cms = parse(text)
        pwshcmd = translate(cms)
        writing(pwshcmd)
        execute()
    except Exception as e:
        print("Error:", e)


if __name__ == "__main__":
    main()
